// config.h - Generated by EX-Installer v0.0.18 for EX-CommandStation v5.0.9-Prod

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD
#define LCD_DRIVER 0x27,20,4
#define WIFI_HOSTNAME "PDMPD"
#define WIFI_SSID "PDMPD"
#define WIFI_PASSWORD "challenge100"
#define ENABLE_WIFI true
#define WIFI_CHANNEL 8
