// myAutomation.h

#include "myAliases.h"
#include "myTurnouts.h"

SEQUENCE(1)	// ID
AUTOSTART
LCD(0, " Porth Dinllaen MPD ")
LCD(4, "  Version  241128c  ")
LCD(5, "Passwd: challenge100")
DONE

SEQUENCE(2) // Heartbeat
AUTOSTART
SET(HEARTBEAT)
DELAY(5)
RESET(HEARTBEAT)
DELAY(995)
FOLLOW(2)
DONE

SEQUENCE(200)   // Operates turnoutS
AUTOSTART
IF(T1BUTTON)	
    IFTHROWN(T1)
        CLOSE(T1)
		RESET(T1TLED)
		SET(T1CLED)
    ELSE
        THROW(T1)
		SET(T1TLED)
		RESET(T1CLED)
    ENDIF
ENDIF
IF(T2BUTTON)
    IFTHROWN(T2)
        CLOSE(T2)
		RESET(T2TLED)
		SET(T2CLED)
    ELSE
        THROW(T2)
		SET(T2TLED)
		RESET(T2CLED)
    ENDIF
ENDIF
IF(T3BUTTON)
    IFTHROWN(T3)
        CLOSE(T3)
		RESET(T3TLED)
		SET(T3CLED)
    ELSE
        THROW(T3)
		SET(T3TLED)
		RESET(T3CLED)
    ENDIF
 ENDIF
IF(T4BUTTON)
    IFTHROWN(T4)
        CLOSE(T4)
		RESET(T4TLED)
		SET(T4CLED)
    ELSE
        THROW(T4)
		SET(T4TLED)
		RESET(T4CLED)
    ENDIF
 ENDIF
IF(T5BUTTON)
    IFTHROWN(T5)
        CLOSE(T5)
		RESET(T5TLED)
		SET(T5CLED)
    ELSE
        THROW(T5)
		SET(T5TLED)
		RESET(T5CLED)
    ENDIF
 ENDIF
IF(T6BUTTON)
    IFTHROWN(T6)
        CLOSE(T6)
		RESET(T6TLED)
		SET(T6CLED)
    ELSE
        THROW(T6)
		RESET(T6TLED)
		SET(T6CLED)
    ENDIF
 ENDIF
IF(SIGNALBUTTON)
    IFTHROWN(SIGNAL)
        CLOSE(SIGNAL)
		RESET(SIGNALREDLED)
		SET(SIGNALGREENLED)
    ELSE
        THROW(SIGNAL)
		RESET(SIGNALREDLED)
		SET(SIGNALGREENLED)
    ENDIF
 ENDIF
 DELAY(BUTTONDELAY)
 FOLLOW(200)
 DONE
